import AuthContextProvider from "./context/AuthContext";
import CreateContextProvider from "./context/CreateContext";
import TagsContextProvider from "./context/TagsContext";
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <AuthContextProvider>
          <TagsContextProvider>
            <CreateContextProvider>{children}</CreateContextProvider>
          </TagsContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
