import "./globals.css";
import { Montserrat } from "next/font/google";
import Providers from "./providers";
import ThemeUIProvider from "./context/ThemeUIContext";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "School Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <ThemeUIProvider>
          <Providers>{children}</Providers>
        </ThemeUIProvider>
      </body>
    </html>
  );
}
